name: Test
on:
  push:
    branches: ["master"]
    pull_request:
      types:
        - opened
        - edited
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix --extra-experimental-features 'nix-command flakes' develop nixpkgs#celluloid --command bash -c 'meson setup build && ninja -C build test'
